# This is a basic workflow to help you get started with Actions

name: crDroid_build_kernel

# Controls when the workflow will run

env:
  KERNEL_SOURCE: 'https://github.com/crdroidandroid/android_kernel_xiaomi_cepheus'
  KERNEL_SOURCE_BRANCH: '13.0'
  KERNEL_DEFCONFIG: 'cepheus_defconfig'
  KERNEL_NAME: 'crDroid'
 
on:
  schedule:
    - cron: '*/5  * * * *'
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#     inputs:
#       KERNEL_SOURCE: 
#         description: 'Kernel Source'
#         required: true
#         default: 'https://github.com/crdroidandroid/android_kernel_xiaomi_cepheus'
        
#       KERNEL_SOURCE_BRANCH:
#         description: 'Branch'
#         required: true
#         default: '13.0'
      
#       KERNEL_DEFCONFIG:
#         description: 'Defconfig'
#         required: true
#         default: 'cepheus_defconfig'
      
#       KERNEL_NAME:
#         required: false
#         default: 'crDroid'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      
      - name: run build script
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M%S")" >> $GITHUB_ENV
          bash scripts/Evasi0nKernelBuild.sh ${{env.KERNEL_SOURCE}} ${{env.KERNEL_SOURCE_BRANCH}} ${{env.KERNEL_DEFCONFIG}} ${{env.KERNEL_NAME}} 
          
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ env.BUILD_TIME }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            kernel_workspace/android-kernel/out/*.zip

