name: PixelOS_build_kernel
env:
  KERNEL_SOURCE: 'https://github.com/balgxmr/kernel_xiaomi_cepheus'
  KERNEL_SOURCE_BRANCH: 'thirteen'
  KERNEL_DEFCONFIG: 'cepheus_defconfig'
  KERNEL_NAME: 'pixelOS-cepheus'
  
on:

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: download kernel source
        run: |
          cd $GITHUB_WORKSPACE && mkdir kernel_workspace && cd kernel_workspace
          git clone ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1

      - name: setup build kernel environment
        run: |
          
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          cp $GITHUB_WORKSPACE/patch/pixelOS_kernel/anykernel.sh $GITHUB_WORKSPACE/patch/pixelOS_kernel/build.sh $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          sed -i "s/KERNEL_NAME=.*/KERNEL_NAME=${KERNEL_NAME}-"$(date "+%Y%m%d%H%M%S")"/g" build.sh
          
          
      - name: add kernelsu 
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          #echo "CONFIG_MODULES=y" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
          echo "CONFIG_KPROBES=y" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
          echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
          echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}

          #curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          git clone https://github.com/nozomanai/KernelSU.git
          bash KernelSU/kernel/setup.sh
          
      - name: build kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          rm .git -R
          sudo bash build.sh
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M%S")" >> $GITHUB_ENV
          
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{env.KERNEL_NAME}}-${{env.BUILD_TIME}}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            kernel_workspace/android-kernel/out/*.zip
